/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ether_openglnativedemo_EGLCRenderer */

#ifndef _Included_com_example_ether_openglnativedemo_EGLCRenderer
#define _Included_com_example_ether_openglnativedemo_EGLCRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ether_openglnativedemo_EGLCRenderer
 * Method:    createEGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ether_openglnativedemo_EGLCRenderer_createEGL
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_openglnativedemo_EGLCRenderer
 * Method:    destroyEGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ether_openglnativedemo_EGLCRenderer_destroyEGL
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_openglnativedemo_EGLCRenderer
 * Method:    draw
 * Signature: (Ljava/lang/Object;IILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ether_openglnativedemo_EGLCRenderer_draw
  (JNIEnv *, jobject, jobject, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
