/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ether_openglnativedemo_MyRenderer */

#ifndef _Included_com_example_ether_openglnativedemo_MyRenderer
#define _Included_com_example_ether_openglnativedemo_MyRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ether_openglnativedemo_MyRenderer
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ether_openglnativedemo_MyRenderer_create
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_ether_openglnativedemo_MyRenderer
 * Method:    draw
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_example_ether_openglnativedemo_MyRenderer_draw
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_example_ether_openglnativedemo_MyRenderer
 * Method:    change
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_ether_openglnativedemo_MyRenderer_change
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
