/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ether_opensldemo_OpenSLTest */

#ifndef _Included_com_example_ether_opensldemo_OpenSLTest
#define _Included_com_example_ether_opensldemo_OpenSLTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ether_opensldemo_OpenSLTest
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ether_opensldemo_OpenSLTest_create
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_opensldemo_OpenSLTest
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ether_opensldemo_OpenSLTest_play
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
