/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ether_ffmpegdemo_FFmpegTest */

#ifndef _Included_com_example_ether_ffmpegdemo_FFmpegTest
#define _Included_com_example_ether_ffmpegdemo_FFmpegTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ether_ffmpegdemo_FFmpegTest
 * Method:    avcodecInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ether_ffmpegdemo_FFmpegTest_avcodecInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_ffmpegdemo_FFmpegTest
 * Method:    avformatInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ether_ffmpegdemo_FFmpegTest_avformatInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_ffmpegdemo_FFmpegTest
 * Method:    avfilterInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ether_ffmpegdemo_FFmpegTest_avfilterInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
