/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ether_ndkplayer_EGLCRenderer */

#ifndef _Included_com_example_ether_ndkplayer_EGLCRenderer
#define _Included_com_example_ether_ndkplayer_EGLCRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ether_ndkplayer_EGLCRenderer
 * Method:    configEGLContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ether_ndkplayer_EGLCRenderer_configEGLContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_ndkplayer_EGLCRenderer
 * Method:    destroyEGLContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ether_ndkplayer_EGLCRenderer_destroyEGLContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ether_ndkplayer_EGLCRenderer
 * Method:    draw
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ether_ndkplayer_EGLCRenderer_draw
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
